title: The Throne of Grace
description: Bible Study Plan - Friday Feb 27, 2026

markdown: kramdown

plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/minimal-mistakes
# Popular, flexible theme suitable for portfolios, documentation, and study sites

