title: The Throne of Grace
description: Bible Study Plan - Friday Feb 27, 2026

markdown: kramdown

plugins:
  - jekyll-remote-theme

remote_theme: johno/pixyll
# Pixyll simple contentâ€‘focused Jekyll theme

